invoice/urls.py
#  Copyright (c) 2022. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#  Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.
#  Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.
#  Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.
#  Vestibulum commodo. Ut rhoncus gravida arcu.

from django.contrib import admin
from django.urls import path
from .views import est_json_customers_url,est_add_client,est_view_tax_estimate_detail, est_apro_cms_page, est_apro_hosting_page, est_apro_it_solutions_page, \
    est_apro_rigs_page, est_products_services_tax_estimates_view, est_export_products_services, \
    est_create_non_tax_invoice, est_tax_update, est_tax_update_record, est_create_tax_invoice, est_list_all_users, \
    est_my_profile, est_delete_tax_estimate, est_tax_estimates_view, est_create_new_account, est_json_users_url, \
    est_logout, est_server_status, createInvoice1, generate_PDF1, SystemStatus, view_PDF1, UserAccount, update1, \
    do_register, JSONEstimatesListView, est_json_customers_list_view, JSONUsersListView, change_password, \
    register_new_account, est_dashboard, updaterecord1, deleteInvoice1, Services, \
    Invoice_List_View_1_date_negative, est_export_customers, est_json_users_list_view, est_export_users, \
    Invoice_List_View_1_date_positive, UserView, est_login, est_change_password
from .views import InvoiceListView2, createInvoice2, generate_PDF2, view_PDF2, deleteInvoice2, logout
from django.conf.urls import include
from .views import export_customers, export_users
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404
from . import views
from django.contrib.auth import views
from django.urls import path


app_name = 'invoice'
urlpatterns = [

    path('invoice-filter-date-negative', Invoice_List_View_1_date_negative.as_view(),
         name="invoice-list-date-negative"),
    path('invoice-filter-date-positive', Invoice_List_View_1_date_positive.as_view(),
         name="invoice-list-date-positive"),
    path('invoicelist', InvoiceListView2.as_view(), name="invoice-list-2"),
    path('users-list', UserView.as_view(), name="users-list"),
    path('create-tax-estimate/', createInvoice1, name="invoice-create-tax-estimate"),
    path('createnotax/', createInvoice2, name="invoice-create-2"),
    path('invoice-detail/<id>', view_PDF1, name='invoice-detail'),
    path('invoice-detail-notax/<id>', view_PDF2, name='invoice-detail-2'),
    path('invoice-download/<id>', generate_PDF1, name='invoice-download'),
    path('invoice-download-notax/<id>', generate_PDF2, name='invoice-download-2'),
    path('invoice-delete/<id>', deleteInvoice1, name='invoice-delete'),
    path('invoice-delete-notax/<id>', deleteInvoice2, name='invoice-delete-2'),
    path('update/<int:id>', update1, name='update'),
    path('update/updaterecord/<int:id>', updaterecord1, name='updaterecord'),
    path('system-status', SystemStatus.as_view(), name='system-status'),

    path('our-services', Services.as_view(), name='our-services'),

    path('export-customers/', export_customers, name='export-customers'),
    path('export-users/', export_users, name='export-users'),

    path("tax-estimates-api", JSONEstimatesListView.as_view(), name='tax-estimates-api'),
    path("users-api", JSONUsersListView.as_view(), name='users-api'),

    path("user-account", UserAccount.as_view(), name='user-account'),

    path('logout/', logout, name='logout'),

    path('register-new-account', register_new_account, name='register-new-account'),
    path('register', do_register, name='register'),

    path('password-change/', change_password, name='password-change'),

    path("", est_dashboard.as_view(), name='dashboard'),
    path("apro-rigs/", est_apro_rigs_page.as_view(), name='apro-rigs'),
    path("apro-it-solutions/", est_apro_it_solutions_page.as_view(), name='apro-it-solutions'),
    path("apro-hosting/", est_apro_hosting_page.as_view(), name='apro-hosting'),
    path("apro-cms/", est_apro_cms_page.as_view(), name='apro-cms'),

    path("sign-in", est_login, name='sign-in'),
    path('sign-out/', est_logout, name='sign-out'),
    path('server-details/', est_server_status.as_view(), name='server-details'),
    path('change-password/', est_change_password, name='change-password'),
    path('export-customers-data/', est_export_customers, name='export-customers-data'),
    path('export-product-service-data/', est_export_products_services, name='export-product-service-data'),

    path('export-users-data/', est_export_users, name='export-users-data'),
    path("customers-api-view/", est_json_customers_list_view.as_view(), name='customers-api-view'),
    path("users-api-view", est_json_users_list_view.as_view(), name='users-api-view'),
    path("customers-api-url/", est_json_customers_url.as_view(), name='customers-api-url'),
    path("users-api-url/", est_json_users_url.as_view(), name='users-api-url'),
    path("create-new-user/", est_create_new_account, name='create-new-user'),
    path("view-estimates/", est_tax_estimates_view.as_view(), name='view-estimates'),
    path("view-products-services-tax-estimates/", est_products_services_tax_estimates_view.as_view(),
         name='view-products-services-tax-estimates'),
    path('view-tax-estimate-detail/<id>', est_view_tax_estimate_detail, name='view-tax-estimate-detail'),
    path('estimate-delete-forever/<id>', est_delete_tax_estimate, name='estimate-delete-forever'),
    path('my-profile-view/', est_my_profile.as_view(), name='my-profile-view'),
    path('view-all-users-list/', est_list_all_users.as_view(), name='view-all-users-list'),
    path('create-new-estimate/', est_create_tax_invoice, name='create-new-estimate'),
    path('create-new-non-tax-estimate/', est_create_non_tax_invoice, name='create-new-non-tax-estimate'),
    path('create-new-client/', est_add_client, name='create-new-client'),


    path('update-record/<int:id>', est_tax_update, name='update-record'),
    path('update-record/updaterecord/<int:id>', est_tax_update_record, name='update-record-a'),



]

mysite/urls.py
#  Copyright (c) 2022. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#  Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.
#  Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.
#  Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.
#  Vestibulum commodo. Ut rhoncus gravida arcu.

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("invoice.urls")),



]

invoice/views.py
#  Copyright (c) 2022. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
#  Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.
#  Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.
#  Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.
#  Vestibulum commodo. Ut rhoncus gravida arcu.

# FROM SECTION
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.template.loader import get_template
from django.http import HttpResponse
from django.contrib.auth import login, forms
from django.contrib import messages
from django.views import View
from .models import LineItem1, Invoice1, LineItem2, Invoice2, Customers
from .forms import LineItemFormset1, InvoiceForm1, LineItemFormset2, InvoiceForm2
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import User
from django.contrib import auth
from datetime import datetime
from braces.views import LoginRequiredMixin, SuperuserRequiredMixin
from django.http import HttpResponseRedirect

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib.auth.forms import UserCreationForm

# IMPORT SECTION
import pdfkit
import csv
import bleach
import logging
import psutil
import platform
import socket
import platform
import cgitb

import time
from django.core.serializers import serialize
from django.http import JsonResponse
from django.views.generic import View
from django.contrib.auth import get_user_model

from django.db.models import Sum




cgitb.enable()
hostname = socket.gethostname()
IPAddress = socket.gethostbyname(hostname)

ALLOWED_TAGS = []
ALLOWED_ATTRIBUTES = {}

#Login Function
def est_login(request):
    request_method = request.method
    if request_method == 'POST':
        user_name = request.POST.get('username', '')
        user_password = request.POST.get('password', '')
        secure_username = bleach.clean(user_name, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES, strip=True,
                                       strip_comments=True)
        user = auth.authenticate(request, username=secure_username, password=user_password)
        if user is not None:
            auth.login(request, user)
            response = HttpResponseRedirect('/')
            return response
        else:
            return render(request, 'invoice/est-login.html', {'wrong_password': True})
    else:
        return render(request, 'invoice/est-login.html')

#Logout Function
@login_required(login_url="/sign-in")
def est_logout(request):
    auth_logout(request)
    return redirect("/sign-in")

#Dashboard Function
class est_dashboard(LoginRequiredMixin, View):
    login_url = "/sign-in"

    def get(self, *args, **kwargs):
        # start = time.time()
        # time.sleep(1)
        # loadingtime = time.time() - start
        users = User.objects.all().order_by("-id")[:6]
        invoices1 = Invoice1.objects.all().order_by("-id")[:5]
        customers = Customers.objects.all().order_by("-id")[:5]
        lineitem1 = LineItem1.objects.all().order_by("-id")[:6]
        estimate_users_total_count = User.objects.count()
        administrator = User.objects.filter(is_superuser=1).count()
        staff = User.objects.filter(is_staff=1).count()
        tax_estimate_total_count = Invoice1.objects.count()
        context = {
            "title": "APRO Estimate - Dashboard",
            "logo_name": "APRO ESTIMATE",
            "lineitem1": lineitem1,
            "customers":customers,
            "tax_estimate_total_count": tax_estimate_total_count,
            "estimate_users_total_count": estimate_users_total_count,

            "users": users,
            "invoices1": invoices1,
            # "page_render": loadingtime,

            "current_ip_address": IPAddress,
            "total_administrator": administrator,
            "total_staff": staff,
            "user_level": "Administrator",
            "main_title": "APRO ESTIMATE",
            "css_link_a": "https://fonts.googleapis.com/icon?family=Material+Icons",
            "css_link_b": "static\css\style.css",
            "css_link_c": "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css",
            "css_link_d": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
            "css_link_e": "static\css\main.css",
            "image_src_a": "https://media-exp1.licdn.com/dms/image/C4D03AQEw4CeRYGE1Fg/profile-displayphoto-shrink_200_200/0/1602676941276?e=1655337600&v=beta&t=SYbeRRL8MilPLKuOpl5EG1U6nBtAtw5pLb3G_sQXqo4",
            "title_a": "Dashboard",
            "create": "CREATE",
            "tax_estimate": "TAX ESTIMATE",
            "view": "VIEW",
            "tax_view_estimate": "VIEW TAX ESTIMATES",
            "export": "EXPORT",
            "sort_by_date_positive": "SORT BY DATE (+)",
            "sort_by_date_negative": "SORT BY DATE (-)",
            "title_f": "Admin Panel",
            "export_customers_csv": "EXPORT CUSTOMERS AS CSV",
            "export_users": "EXPORT USERS AS CSV",
            "sort": "SORT",
            "system_status": "SYSTEM STATUS",
            "title_view_users": "View Users",
            "title_create_users": "Create Users",
            "title_change_password": "Change Password",
            "title_i": "Create New Tax Based Estimate",
            "title_j": "More Info",
            "title_k": "View Tax Estimates",
            "logout": "LOGOUT",
            "errors": "Errors",
            "title_m": "Total Users/Administrator/Staff",
            "table_head_a": "CUSTOMER ID",
            "table_head_b": "DATE",
            "table_head_c": "CUSTOMER NAME",
            "table_head_d": "SERVICE TYPE",
            "table_head_e": "GST(%)",
            "table_head_f": "TOTAL",
            "table_head_excluded_GST": "(excluded GST)",
            "table_head_included_GST": "(included GST)",
            "table_head_view": "View",
            "table_head_edit": "Edit",
            "table_head_delete": "Delete",
            "table_head_download": "Download",
        }
        # RENDER AND SHOW OUTPUT TO INVOICE-LIST.HTML
        return render(self.request, "invoice/est-dashboard.html", context)

    def post(self, request):
        # import pdb;pdb.set_trace()
        invoice1_ids = request.POST.getlist("invoice1_id")

        invoice1_ids = list(map(int, invoice1_ids))
        invoices1 = Invoice1.objects.filter(id__in=invoice1_ids)

        # import pdb;pdb.set_trace()
        return redirect("invoice:dashboard")

#APRO Rigs Service Page Function
class est_apro_rigs_page(LoginRequiredMixin, View):
    login_url = "/sign-in"

    def get(self, *args, **kwargs):
        # start = time.time()
        # time.sleep(1)
        # loadingtime = time.time() - start
        users = User.objects.all().order_by("-id")[:6]
        invoices1 = Invoice1.objects.all().order_by("-id")[:5]
        estimate_users_total_count = User.objects.count()
        administrator = User.objects.filter(is_superuser=1).count()
        staff = User.objects.filter(is_staff=1).count()
        tax_estimate_total_count = Invoice1.objects.count()

        context = {
            "title": "APRO Estimate - Dashborad",
            "logo_name": "APRO ESTIMATE",

            "tax_estimate_total_count": tax_estimate_total_count,
            "estimate_users_total_count": estimate_users_total_count,

            "users": users,
            "invoices1": invoices1,
            # "page_render": loadingtime,

            "current_ip_address": IPAddress,
            "total_administrator": administrator,
            "total_staff": staff,
            "user_level": "Administrator",
            "main_title": "APRO ESTIMATE",
            "css_link_a": "https://fonts.googleapis.com/icon?family=Material+Icons",
            "css_link_b": "static\css\style.css",
            "css_link_c": "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css",
            "css_link_d": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css",
            "css_link_e": "static\css\main.css",
            "image_src_a": "https://media-exp1.licdn.com/dms/image/C4D03AQEw4CeRYGE1Fg/profile-displayphoto-shrink_200_200/0/1602676941276?e=1655337600&v=beta&t=SYbeRRL8MilPLKuOpl5EG1U6nBtAtw5pLb3G_sQXqo4",
            "title_a": "Dashboard",
            "create": "CREATE",
            "tax_estimate": "TAX ESTIMATE",
            "view": "VIEW",
            "tax_view_estimate": "VIEW TAX ESTIMATES",
            "export": "EXPORT",
            "sort_by_date_positive": "SORT BY DATE (+)",
            "sort_by_date_negative": "SORT BY DATE (-)",
            "title_f": "Admin Panel",
            "export_customers_csv": "EXPORT CUSTOMERS AS CSV",
            "export_users": "EXPORT USERS AS CSV",
            "sort": "SORT",
            "system_status": "SYSTEM STATUS",
            "title_view_users": "View Users",
            "title_create_users": "Create Users",
            "title_change_password": "Change Password",
            "title_i": "Create New Tax Based Estimate",
            "title_j": "More Info",
            "title_k": "View Tax Estimates",
            "logout": "LOGOUT",
            "errors": "Errors",
            "title_m": "Total Users/Administrator/Staff",
            "table_head_a": "CUSTOMER ID",
            "table_head_b": "DATE",
            "table_head_c": "CUSTOMER NAME",
            "table_head_d": "SERVICE TYPE",
            "table_head_e": "GST(%)",
            "table_head_f": "TOTAL",
            "table_head_excluded_GST": "(excluded GST)",
            "table_head_included_GST": "(included GST)",
            "table_head_view": "View",
            "table_head_edit": "Edit",

invoice/templates/Backup Code/invoice-list.html
{% extends 'invoice/base.html' %}
{% load static %}
{% block content %}



<!--
  ~ Copyright (c) 2022. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  ~ Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.
  ~ Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.
  ~ Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.
  ~ Vestibulum commodo. Ut rhoncus gravida arcu.
  -->

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="{% static 'css/invoicelist.css' %}" rel="stylesheet">

<div class="columns is-centered has-text-centered">
    <div class="column is-half">
        <div class="card has-background-white-ter">
            <h1 class="title is-3"></h1>
        </div>
    </div>
</div>



<!--Logo Start Section-->
<div class="classone" ><object data="http://apropack.com/assets/apro-it.svg" width="300" height="auto"> </object>
<!--Time or Clock Start Section-->
     <div class="classone" ><span id="clock"></span></div><br>
<!--Time or Clock End Section-->
<!--Title Start Section-->
                <p class="classtwo">Tax Based Estimates</p> <br>
<!--Title End Section-->
</div>
<!--Logo End Section-->

<!--Time or Clock JavaScript Start Section-->
<script type="text/javascript">
    var clockElement = document.getElementById('clock');

    function clock() {
        clockElement.textContent = new Date().toString();
    }
    setInterval(clock, 1000);
</script>
<!--Time or Clock JavaScript End Section-->




<form action="{% url 'invoice:invoice-list' %}" method="post">
    {% csrf_token %}

    <div class="card">
        <header class="card-header" style="display:block-ruby;">
            <p class="card-header-title">
                Estimate Generator v1 <br>&nbsp;
                <div class="classfour"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large">
                <a href="{% url 'invoice:invoice-create' %}" class="has-text-white classthree" >Create New Tax Based Estimate</a>
                </button></div>

<!--           <div style="padding:10px;"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large"> &lt;!&ndash;  <button class="button is-rounded is-info">&ndash;&gt;-->
<!--                <a href="{% url 'invoice:invoice-create-2' %}" class="has-text-white" style="font-size: 11px;-->
<!--font-weight: bold;">Create New Non Tax Based Estimate</a>-->
<!--                </button></div>-->
            <div class="classfive"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large">
                <a href="{% url 'invoice:invoice-list' %}" class="has-text-white classthree" >View Tax Estimates</a>
                </button></div>
             <div class="classfive"><button title="Logout" class="w3-btn w3-white w3-border w3-border-red w3-round-large">
                <a href="{% url 'invoice:logout' %}" class="has-text-white classthree" > Logout</a>
                </button></div>
<!--            <div style="padding:10px;"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large">-->
<!--                <a href="{% url 'invoice:invoice-list-2' %}" class="has-text-white" style="font-size: 11px;-->
<!--font-weight: bold;">View Non Tax Estimates</a>-->
<!--                </button></div>-->


<!--                <div><button class="button is-rounded is-info">-->
<!--                <a href="{% url 'invoice:invoice-list-2' %}" class="has-text-white">View Non Tax Estimates</a>-->
<!--                </button></div>-->


            </p>


        </header>



         <header class="card-header" >
  <p class="card-header-title">
                <br>&nbsp;

           <div class="classfive"><button  class="w3-btn w3-white w3-border w3-border-red w3-round-large"> <!--  <button class="button is-rounded is-info">-->
                <a href="{% url 'invoice:invoice-list-date-negative' %}" class="has-text-white classthree" >Filter by Date (+)</a>
                </button></div>
             <div class="classfive"><button  class="w3-btn w3-white w3-border w3-border-red w3-round-large"> <!--  <button class="button is-rounded is-info">-->
                <a href="{% url 'invoice:invoice-list-date-positive' %}" class="has-text-white classthree" >Filter by Date (-)</a>
                </button></div>

     <div class="classfive"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large">
                <a href="#" class="has-text-white classthree" >Search</a>
                </button></div>


         <div class="classfive"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large">
                <a href="/admin" class="has-text-white classthree" >Admin Panel</a>
                </button></div>

       <div class="classfive"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large">
                <a href="{% url 'invoice:export' %}" class="has-text-white classthree" >Export As CSV</a>
                </button></div>
   <div class="classfive"><button class="w3-btn w3-white w3-border w3-border-red w3-round-large">
                <a href="{% url 'invoice:export' %}" class="has-text-white classthree" >Export As PDF</a>
                </button></div>
<!--                <div><button class="button is-rounded is-info">-->
<!--                <a href="{% url 'invoice:invoice-list-2' %}" class="has-text-white">View Non Tax Estimates</a>-->
<!--                </button></div>-->





        </header>





        <div class="card-content-edited">
            <div class="content">

                <table class="table is-fullwidth is-bordered is-hoverable is-striped" id="myTable">
                    <tbody>
                    <thead>
                        <tr>
                            <th></th>

                            <th style="text-align:center;">CUSTOMER ID</th>
                            <th style="text-align:center;">DATE</th>
                            <th style="text-align:center;">CUSTOMER NAME </th>
                            <th style="text-align:center;">SERVICE TYPE</th>

<!--                            <th>DATE</th>-->

                            <th style="text-align:center;">GST(%)</th>
                            <th style="text-align:center;">TOTAL <br>(excluded GST)</th>
                            <th style="text-align:center;">TOTAL <br>(included GST)</th>

                            <th style="text-align:center;">View</th>
                            <th style="text-align:center;">Edit</th>
                            <th style="text-align:center;color:red;">Delete</th>
                            <th style="text-align:center;">Download</th>


                        </tr>
                    </thead>
                    {% for invoice1 in invoices1 %}
                    <tr>
                        <td><input class="checkbox" type="checkbox" value="{{invoice1.id}}" name="invoice1_id" size="2" /></td>

                        <td width="10%" style="text-align:center;vertical-align: middle;">{{invoice1.id}}</td>
                        <td width="10%" style="text-align:center;vertical-align: middle;">{{invoice1.date}}</td>
                        <td width="39%" style="text-align:center;vertical-align: middle;">{{invoice1.customer}}</td>
                        <td width="39%" style="text-align:center;vertical-align: middle;"><img class="service-img" src="{{invoice1.service}}"></td>

<!--                        <td width="39%"> {{invoice1.date}}</td>-->
 <td style="text-align:center;vertical-align: middle;">{{invoice1.gstpercentage}}%</td>

                        <td style="text-align:center;vertical-align: middle;">{{invoice1.currency}}<br>{{invoice1.total_amount}}</td>
                         <td style="text-align:center;vertical-align: middle;">{{invoice1.currency}}<br> {{invoice1.subtotal}}</td>
                        <!--<td class="level-right">
                            {% if invoice.get_status %}
                            <a class="button is-small is-success" href="#">Paid</a>
                            {% else %}
                            <a class="button is-small is-warning" href="#">Not Paid</a>
                            {% endif %}
                        </td>-->
                           <td width="1%">
                            <a class="w3-btn w3-white w3-border w3-border-red w3-round-large" href="{% url 'invoice:invoice-detail' id=invoice1.id %}" style="box-shadow: 0 0 3px 3px #0ab6d921;
border-radius: 73px;">
<!--                                <a href="{% url 'invoice:invoice-detail' id=invoice1.id %}">-->
                                <div style="font-weight:bold;font-size:10px;"><i class="material-icons">remove_red_eye</i></div>
<!--                                <div class="button is-small is-info">View</div>-->
                            </a>
                        </td>   <td width="1%">
                            <a class="w3-btn w3-white w3-border w3-border-red w3-round-large" href="{% url 'invoice:update' id=invoice1.id %}" style="box-shadow: 0 0 3px 3px #0ab6d921;
border-radius: 73px;">
                                <div style="font-weight:bold;font-size:10px;"><i class="material-icons">edit</i></div>
                            </a>
                        </td>

                         <td width="1%">

                            <a class="w3-btn w3-white w3-border w3-border-red w3-round-large" href="{% url 'invoice:invoice-delete' id=invoice1.id %}" style="box-shadow: 0 0 3px 3px #0ab6d921;
border-radius: 73px;">

                                <div style="font-weight:bold;font-size:10px;color:red;"><i class="material-icons">delete_forever</i></div>
                            </a>


                        </td>



                        <td width="1%">
                            <a class="w3-btn w3-white w3-border w3-border-red w3-round-large" href="{% url 'invoice:invoice-download' id=invoice1.id %}" style="box-shadow: 0 0 3px 3px #0ab6d921;
border-radius: 73px;">
                                <div style="font-weight:bold;font-size:10px;"><i class="material-icons">file_download</i></div>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div><br /><br /><br />
    <!--<div class="card has-background-white-ter">
        <header class="card-header">
            <p class="card-header-title">
                Change Order Status
            </p>
        </header>
        <div class="card-content">
            <div class="select is-rounded">
                <select id="status" name="status">
                    <option value="1">Paid</option>
                    <option value="0">Not Paid</option>
                </select>
            </div>
            <input class="button  is-info is-rounded" type="submit" class="btn" value="Change Status" name="mybtn">
        </div>
    </div>-->
</form>

{% endblock content %}